/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.ListaEmpleados;
import Control.ListaEmpleados;
import Personas.Empleados;
import javax.swing.JOptionPane;

/**
 *
 * @author galla
 */
public class JfEmpleado extends javax.swing.JFrame {
    
 private final ListaEmpleados lista = new ListaEmpleados();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfEmpleado.class.getName());

    /**
     * Creates new form JfEmpleado
     */
    public JfEmpleado() {
        initComponents();
        refrescarTabla();
    }
        private void refrescarTabla() {
    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) tblEmpleados.getModel();

    // borra filas actuales
    m.setRowCount(0);

    // llena con los datos de la lista
    for (Empleados e : lista.getListEmpleado()) {
        m.addRow(new Object[]{
            e.getCedula(),
            e.getNombre(),
            formatearFecha(e.getFechaNacimiento()), 
            e.getTelefono(),
            e.getCorreo(),
            e.getPuesto(),
            e.getSalario()
        });
    }
}
        private String formatearFecha(java.time.LocalDate fecha) {
    if (fecha == null) return "";
    java.time.format.DateTimeFormatter f =
        java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
    return fecha.format(f);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        spFecha = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPanel.setBackground(new java.awt.Color(255, 204, 0));
        FondoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cedula");
        FondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel2.setText("Nombre");
        FondoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel3.setText("Fecha de nacimiento");
        FondoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel4.setText("Telefono");
        FondoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        txtCedula.setBackground(new java.awt.Color(255, 153, 51));
        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FondoPanel.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 300, -1));

        txtNombre.setBackground(new java.awt.Color(255, 153, 51));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        FondoPanel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 300, -1));

        txtTelefono.setBackground(new java.awt.Color(255, 153, 51));
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FondoPanel.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 290, -1));

        spFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1755108000000L), null, new java.util.Date(1787030520000L), java.util.Calendar.YEAR));
        spFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spFecha.setEditor(new javax.swing.JSpinner.DateEditor(spFecha, "dd/MM/yyyy"));
        FondoPanel.add(spFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 300, -1));

        jLabel5.setText("Correo");
        FondoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 37, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 153, 51));
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        FondoPanel.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 290, -1));

        jLabel6.setText("Puesto");
        FondoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 37, -1));

        txtPuesto.setBackground(new java.awt.Color(255, 153, 51));
        txtPuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FondoPanel.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 290, -1));

        jLabel7.setText("Salario");
        FondoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        txtSalario.setBackground(new java.awt.Color(255, 153, 51));
        txtSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        FondoPanel.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 300, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-user-male-50.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Eliminar1 (3).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-contacts-50.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/actualizar.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-broom-50.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addGap(81, 81, 81))
        );

        FondoPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 610));

        tblEmpleados.setBackground(new java.awt.Color(255, 204, 0));
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Fecha Nacimiento", "Telefono", "Correo", "Puesto", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        FondoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 460, 780, 108));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hertz anuncio.jpeg"))); // NOI18N
        FondoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 230, 320));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/images.png"))); // NOI18N
        FondoPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
        String cedula = txtCedula.getText().trim();
        Empleados e = lista.find(cedula);
        if (e == null) { // o captura tu NoEncontradoException
            JOptionPane.showMessageDialog(this, "No existe empleado con esa cédula");
            return;
        }
        // Pasa datos al formulario
        txtNombre.setText(e.getNombre());
        txtTelefono.setText(e.getTelefono());
        txtCorreo.setText(e.getCorreo());
        txtPuesto.setText(e.getPuesto());
        txtSalario.setValue(e.getSalario());
        java.util.Date d = java.util.Date.from(e.getFechaNacimiento().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant());
        spFecha.setValue(d);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       try {
        String cedula = txtCedula.getText().trim();
        Empleados e = lista.find(cedula);
        if (e == null) {
            JOptionPane.showMessageDialog(this, "No existe empleado con esa cédula");
            return;
        }
        int x = JOptionPane.showConfirmDialog(this, "¿Eliminar al empleado " + e.getNombre() + "?", 
                                              "Confirmar", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            lista.remove(e);
            refrescarTabla();
            btnLimpiarActionPerformed(null);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
        String cedula = txtCedula.getText().trim();
        String nombre = txtNombre.getText().trim();
        java.util.Date fn = (java.util.Date) spFecha.getValue();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String puesto = txtPuesto.getText().trim();
        double salario = ((Number) txtSalario.getValue()).doubleValue();

        if (cedula.isBlank() || nombre.isBlank() || puesto.isBlank())
            throw new IllegalArgumentException("Cédula, nombre y puesto son obligatorios");

        // Convertir Date -> LocalDate si tu entidad usa LocalDate
        java.time.LocalDate fechaNac = fn.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        // Construye tu Empleados según tu constructor
        Empleados e = new Empleados(cedula, nombre, fechaNac, telefono, correo,puesto, salario);

        // Evitar duplicados (haz la validación en addEmpleado)
        lista.add(e);

        refrescarTabla();
        JOptionPane.showMessageDialog(this, "Empleado agregado");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       try {
        String cedula = txtCedula.getText().trim();
        String tel = txtTelefono.getText().trim();
        String cor = txtCorreo.getText().trim();
        String puesto = txtPuesto.getText().trim();

        // reutiliza tu método de servicio/lista
        // (el que hicimos antes con validaciones)
        lista.actualizarEmpleado(cedula, tel, cor, puesto);
        

        // Si quieres actualizar salario también:
        Empleados e = lista.find(cedula);
        if (e != null) {
            double salario = ((Number) txtSalario.getValue()).doubleValue();
            if (salario < 0) throw new IllegalArgumentException("El salario no puede ser negativo");
            e.setSalario(salario);
        }

        refrescarTabla();
        JOptionPane.showMessageDialog(this, "Empleado actualizado");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    txtCedula.setText("");
    txtNombre.setText("");
    txtTelefono.setText("");
    txtCorreo.setText("");
    txtPuesto.setText("");
    txtSalario.setValue(0.0);
    spFecha.setValue(new java.util.Date());
    tblEmpleados.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spFecha;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
