/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Alquiler.Reserva;
import Control.GestorReservas;
import Control.GestorVehiculos;
import Control.ListaClientes;
import Personas.Clientes;
import Vehiculo.Vehiculos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author galla
 */
public class Jfreserva extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jfreserva.class.getName());
    private GestorReservas gestorReservas;
    private ListaClientes gestorClientes;   
    private GestorVehiculos gestorVehiculos; 
    private DefaultTableModel modeloReservas;
    /**
     * Creates new form Jfreserva
     */
    public Jfreserva() {
        initComponents();
        gestorClientes  = (gestorClientes  != null) ? gestorClientes  : new ListaClientes();
gestorVehiculos = (gestorVehiculos != null) ? gestorVehiculos : new GestorVehiculos();

gestorReservas = new GestorReservas(); // Tu clase sin cambios

// --- Inyectar listClientes por reflexión (SIN tocar GestorReservas) ---
try {
    java.lang.reflect.Field f = GestorReservas.class.getDeclaredField("listClientes");
    f.setAccessible(true);
    // Asigna la lista real de clientes de tu gestor
    f.set(gestorReservas, gestorClientes.getListClientes()); // ajusta getLista() si tu gestor usa otro nombre
} catch (Exception ex) {
    // Si algo falla, al menos evita NPE con una lista vacía
    try {
        java.lang.reflect.Field f = GestorReservas.class.getDeclaredField("listClientes");
        f.setAccessible(true);
        f.set(gestorReservas, new java.util.ArrayList<>());
    } catch (Exception ignore) {}
}

// --- Modelo de tabla para mostrar reservas ---
modeloReservas = new DefaultTableModel(
    new Object[][]{},
    new String[]{"ID", "Cédula", "Placa", "Fecha Reserva", "Inicio", "Estado Vehículo"}
){
    @Override public boolean isCellEditable(int r, int c) { return false; }
};
tblReservas.setModel(modeloReservas);

refrescarTablaReservas();
    }
private Clientes tomarClientePorCedula(String cedula) {
    if (cedula == null || cedula.isBlank()) throw new IllegalArgumentException("Cédula vacía");
    // Ajusta al método real de tu gestor
    Clientes c = gestorClientes.find(cedula);
    if (c == null) throw new IllegalArgumentException("Cliente no existe: " + cedula);
    return c;
}
private java.time.LocalDate parseFecha(String fechaTexto) {
    try {
        return java.time.LocalDate.parse(fechaTexto.trim());
    } catch (Exception e) {
        throw new IllegalArgumentException("Formato de fecha inválido. Use yyyy-MM-dd (ej: 2025-08-29)");
    }
}

private Vehiculos tomarVehiculoPorPlaca(String placa) {
    if (placa == null || placa.isBlank()) throw new IllegalArgumentException("Placa vacía");
    // Ajusta al método real de tu gestor
    Vehiculos v = gestorVehiculos.buscarVehiculo(placa);
    if (v == null) throw new IllegalArgumentException("Vehículo no existe: " + placa);
    return v;
}

private java.time.LocalDate toLocalDate(java.util.Date date) {
    if (date == null) throw new IllegalArgumentException("Fecha no seleccionada");
    return date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
}

private void refrescarTablaReservas() {
    modeloReservas.setRowCount(0);
    for (Reserva r : gestorReservas.getReservas()) {
        modeloReservas.addRow(new Object[]{
            r.getIdReserva(),
            r.getCliente().getCedula(),
            r.getVehiculo().getPlaca(),
            r.getFechaReserva(),   // ajusta getters si se llaman distinto
            r.getFechaInicio(),
            r.getVehiculo().getEstado()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtPlaca = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        idReserva = new javax.swing.JLabel();
        txtIdReserva = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButton1)
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addGap(31, 31, 31)
                .addComponent(jButton4)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 150, 560));

        txtPlaca.setBackground(new java.awt.Color(255, 153, 51));
        txtPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 290, -1));

        txtCedula.setBackground(new java.awt.Color(255, 153, 51));
        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 290, -1));

        jLabel1.setText("Placa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel3.setText("cedula");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        tblReservas.setBackground(new java.awt.Color(255, 204, 51));
        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cedula", "Placa", "Fecha reserva", "inicio", "Estado vehiculo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservas.setSelectionBackground(new java.awt.Color(255, 153, 51));
        jScrollPane1.setViewportView(tblReservas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 660, 90));

        idReserva.setText("IdReserva");
        jPanel1.add(idReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        txtIdReserva.setBackground(new java.awt.Color(255, 153, 51));
        txtIdReserva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtIdReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 290, -1));

        txtFechaInicio.setBackground(new java.awt.Color(255, 153, 51));
        txtFechaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 210, -1));

        txtFechaFin.setBackground(new java.awt.Color(255, 153, 51));
        txtFechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 210, -1));

        jLabel2.setText("FechaFin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel4.setText("FechaInicio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
    String ced = txtCedula.getText().trim();
    String placa = txtPlaca.getText().trim();

    java.time.LocalDate inicio = parseFecha(txtFechaInicio.getText());
    java.time.LocalDate fin    = parseFecha(txtFechaFin.getText());

    Clientes cli = tomarClientePorCedula(ced);
    Vehiculos veh = tomarVehiculoPorPlaca(placa);

    Reserva r = gestorReservas.agregarReserva(cli, veh, inicio, fin);

    javax.swing.JOptionPane.showMessageDialog(this, "Reserva creada. ID: " + r.getIdReserva());
    refrescarTablaReservas();

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila = tblReservas.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una reserva en la tabla");
    return;
}
int id = (int) modeloReservas.getValueAt(fila, 0);
boolean ok = gestorReservas.cancelarReserva(id); // TU método, sin cambios
if (ok) {
    javax.swing.JOptionPane.showMessageDialog(this, "Reserva cancelada");
    refrescarTablaReservas();
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cancelar (ID no encontrado)");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
    int id = Integer.parseInt(txtIdReserva.getText().trim());
    Reserva r = gestorReservas.buscarReservaPorId(id); // TU método, sin cambios
    if (r == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No existe la reserva con ID " + id);
    } else {
        // aquí solo muestro un ejemplo; puedes llenar labels/cajas si quieres
        javax.swing.JOptionPane.showMessageDialog(this,
            "Cliente: " + r.getCliente().getNombre() + " | Vehículo: " + r.getVehiculo().getPlaca());
    }
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Reserva r = gestorReservas.atenderReserva(); // TU método, sin cambios
if (r == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "No hay reservas en cola");
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Atendida reserva ID: " + r.getIdReserva());
    refrescarTablaReservas();
}        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Jfreserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idReserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtIdReserva;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
