/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.GestorVehiculos;
import Vehiculo.EstadoVehiculo;
import Vehiculo.TipoVehiculo;
import Vehiculo.Vehiculos;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author galla
 */
public class JfVehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfVehiculo.class.getName());
    private final GestorVehiculos gestor = new GestorVehiculos();
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form JfVehiculo
     */
    public JfVehiculo() {
        initComponents();
        configurarPantalla();
    }
// En el constructor de JfVehiculos, después de initComponents();
private void configurarPantalla() {
    // 1) Combos
    cmbTipo.removeAllItems();
    for (TipoVehiculo t : TipoVehiculo.values()) cmbTipo.addItem(t);

    cmbEstado.removeAllItems();
    for (EstadoVehiculo e : EstadoVehiculo.values()) cmbEstado.addItem(e);

    // 2) Spinner Año (últimos 20 años hasta el actual)
    int anioActual = java.time.Year.now().getValue();
    spYear.setModel(new javax.swing.SpinnerNumberModel(anioActual, anioActual - 20, anioActual, 1));

    // 3) Tabla no editable
    modeloTabla = new DefaultTableModel(
        new Object[][] {},
        new String[] {"Placa", "Marca", "Modelo", "Año", "Tipo", "Estado"}
    ) {
        @Override public boolean isCellEditable(int row, int column) { return false; }
    };
    tblVehiculos.setModel(modeloTabla);
    tblVehiculos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    // 4) Selección de fila -> cargar a los campos
    tblVehiculos.getSelectionModel().addListSelectionListener(ev -> {
        if (!ev.getValueIsAdjusting()) cargarDesdeFilaSeleccionada();
    });

    refrescarTabla();
}
// Normaliza la placa para hablar con el Gestor/HashMap
private String normalizarPlaca() {
    return txtPlaca.getText().trim().toUpperCase();
}
private void limpiarCampos() {
    txtPlaca.setText("");
    txtMarca.setText("");
    txtModelo.setText("");
    int anioActual = java.time.Year.now().getValue();
    spYear.setValue(anioActual);
    if (cmbTipo.getItemCount() > 0) cmbTipo.setSelectedIndex(0);
    if (cmbEstado.getItemCount() > 0) cmbEstado.setSelectedIndex(0);
    tblVehiculos.clearSelection();
    txtPlaca.setEditable(true);   // por si la deshabilitas al seleccionar
}
private void cargarDesdeFilaSeleccionada() {
    int fila = tblVehiculos.getSelectedRow();
    if (fila < 0) return;

    txtPlaca.setText(String.valueOf(modeloTabla.getValueAt(fila, 0)));
    txtMarca.setText(String.valueOf(modeloTabla.getValueAt(fila, 1)));
    txtModelo.setText(String.valueOf(modeloTabla.getValueAt(fila, 2)));
    spYear.setValue(Integer.parseInt(String.valueOf(modeloTabla.getValueAt(fila, 3))));

    // Si guardas los enums como name() en la tabla, esto funciona directo:
    String tipoStr = String.valueOf(modeloTabla.getValueAt(fila, 4));
    String estadoStr = String.valueOf(modeloTabla.getValueAt(fila, 5));
    cmbTipo.setSelectedItem(TipoVehiculo.valueOf(tipoStr));
    cmbEstado.setSelectedItem(EstadoVehiculo.valueOf(estadoStr));

    // Evita que cambien placa al actualizar/eliminar
    txtPlaca.setEditable(false);
}
private void refrescarTabla() {
    modeloTabla.setRowCount(0);
    for (Vehiculos v : gestor.getVehiculos()) {
        modeloTabla.addRow(new Object[]{
            v.getPlaca(),
            v.getMarca(),
            v.getModelo(),
            v.getYear(),
            v.getTipo().name(),
            v.getEstado().name()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        spYear = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Años = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-folder-50.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Eliminar1 (2).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-browse-folder-50.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/actualizar.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-broom-50.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 560));

        txtPlaca.setBackground(new java.awt.Color(255, 153, 51));
        txtPlaca.setText("placa");
        txtPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 290, -1));

        txtModelo.setBackground(new java.awt.Color(255, 153, 51));
        txtModelo.setText("Modelo");
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 290, -1));

        txtMarca.setBackground(new java.awt.Color(255, 153, 51));
        txtMarca.setText("Marca");
        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 290, -1));

        cmbTipo.setBackground(new java.awt.Color(255, 153, 51));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Pick-Up" }));
        cmbTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 260, -1));

        cmbEstado.setBackground(new java.awt.Color(255, 153, 51));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "En Alquiler", "Mantenimiento" }));
        cmbEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 260, -1));

        spYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(spYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 260, -1));

        jLabel1.setText("Placa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel2.setText("Marca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel3.setText("Modelo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        Años.setText("Años");
        jPanel1.add(Años, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jLabel4.setText("Tipo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel5.setText("Estado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        tblVehiculos.setBackground(new java.awt.Color(255, 204, 51));
        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Placa ", "Marca", "Modelo", "Años", "Tipo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVehiculos.setSelectionBackground(new java.awt.Color(255, 153, 51));
        jScrollPane1.setViewportView(tblVehiculos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 660, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
        String placa = normalizarPlaca();
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        int year = (int) spYear.getValue();
        TipoVehiculo tipo = (TipoVehiculo) cmbTipo.getSelectedItem();
        EstadoVehiculo estado = (EstadoVehiculo) cmbEstado.getSelectedItem();

        Vehiculos v = new Vehiculos(placa, marca, modelo, year, tipo, estado);
        gestor.agregarVehiculo(v);

        refrescarTabla();
        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Vehículo agregado.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
        String placa = normalizarPlaca();
        int r = JOptionPane.showConfirmDialog(this,
                "¿Eliminar vehículo con placa " + placa + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (r != JOptionPane.YES_OPTION) return;

        gestor.eliminarVehiculo(placa);

        refrescarTabla();
        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Vehículo eliminado.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
         try {
        String placa = normalizarPlaca();
        Vehiculos v = gestor.buscarVehiculo(placa);
        if (v == null) {
            JOptionPane.showMessageDialog(this, "No existe vehículo con esa placa.");
            return;
        }

        // Rellenar campos
        txtPlaca.setText(v.getPlaca());
        txtMarca.setText(v.getMarca());
        txtModelo.setText(v.getModelo());
        spYear.setValue(v.getYear());
        cmbTipo.setSelectedItem(v.getTipo());
        cmbEstado.setSelectedItem(v.getEstado());
        txtPlaca.setEditable(false);

        // Seleccionar fila correspondiente en la tabla (si está listada)
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (String.valueOf(modeloTabla.getValueAt(i, 0)).equalsIgnoreCase(v.getPlaca())) {
                tblVehiculos.setRowSelectionInterval(i, i);
                tblVehiculos.scrollRectToVisible(tblVehiculos.getCellRect(i, 0, true));
                break;
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
          try {
        String placa = normalizarPlaca();
        String modelo = txtModelo.getText().trim();
        TipoVehiculo tipo = (TipoVehiculo) cmbTipo.getSelectedItem();
        EstadoVehiculo estado = (EstadoVehiculo) cmbEstado.getSelectedItem();

        gestor.actualizarVehiculo(placa, modelo, tipo, estado);

        refrescarTabla();
        JOptionPane.showMessageDialog(this, "Vehículo actualizado.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       limpiarCampos();
    refrescarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfVehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Años;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spYear;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
